[build]
  publish = "dist/"
  command = "npm run build"
  edge_functions = "./functions"

[context.deploy-preview]
  publish = "dist/"

[dev]
  command = "yarn dev"
  port = 3000
  publish = "dist"

[[edge_functions]]
path = "/matchs"
function = "matchs"